name: check-pr
on:
  push:
    branches:
    - 'master'
  pull_request: {}
jobs:
  check-pr:
    name: check-pr
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.0.0
    - run: npm install
    - run: npm run asbuild